### ISSUE TITLE
效果真的可以

### ISSUE THREAD

**Issue by Ma-Weijian** [fenglinglwb/MAT#117]
感觉比基于SD的方法稳定一点，至少不会引入新的东西

**Comment by foocker** [comment]
> 感觉比基于SD的方法稳定一点，至少不会引入新的东西

?我测试了，效果很垃圾。 您这里啥情况。

**Comment by wangyp33** [comment]
请问你测试他的模型时，有没有遇到加载失败的问题（用官方提供的pkl）
[问题链接](https://github.com/fenglinglwb/MAT/issues/120)
Loading networks from: pretrained/CelebA-HQ_512.pkl
Traceback (most recent call last):
File "generate_image.py", line 157, in
generate_images() # pylint: disable=no-value-for-parameter
File "/home/lianyj/miniconda3/envs/MAT/lib/python3.7/site-packages/click/core.py", line 1157, in call
return self.main(*args, **kwargs)
File "/home/lianyj/miniconda3/envs/MAT/lib/python3.7/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
File "/home/lianyj/miniconda3/envs/MAT/lib/python3.7/site-packages/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/lianyj/miniconda3/envs/MAT/lib/python3.7/site-packages/click/core.py", line 783, in invoke
return _callback(*args, **kwargs)
File "/home/lianyj/miniconda3/envs/MAT/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
return f(get_current_context(), *args, **kwargs)
File "generate_image.py", line 100, in generate_images
G_saved = legacy.load_network_pkl(f)['G_ema'].to(device).eval().requires_grad(False) # type: ignore
File "/home/lianyj/MAT/legacy.py", line 21, in load_network_pkl
data = _LegacyUnpickler(f).load()
_pickle.UnpicklingError: pickle data was truncated
