### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [32, 5, 1, 1], expected input[8, 4, 512, 512] to have 5 channels, but got 4 channels instead

### ISSUE THREAD

**Issue by 136LYJ** [fenglinglwb/MAT#119]
CUDA_VISIBLE_DEVICES=0 python train.py \
    --outdir=/home/data/PersonalData/MAT/result \
    --gpus=1 \
    --batch=8 \
    --metrics=fid36k5_full \
    --data=/home/data/PersonalData/erase/cut/img4/block_n \
    --data_val=/home/data/PersonalData/erase/cut/img4/block_2 \
    --dataloader=datasets.dataset_512.ImageFolderMaskDataset \
    --mirror=True \
    --cond=False \
    --cfg=places512 \
    --aug=noaug \
    --generator=networks.mat.Generator \
    --discriminator=networks.mat.Discriminator \
    --loss=losses.loss.TwoStageLoss \
    --pr=0.1 \
    --pl=False \
    --truncation=0.5 \
    --style_mix=0.5 \
    --ema=10 \
    --lr=0.001
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "train.py", line 648, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/home/lianyj/miniconda3/envs/MAT/lib/python3.7/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/lianyj/miniconda3/envs/MAT/lib/python3.7/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/lianyj/miniconda3/envs/MAT/lib/python3.7/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lianyj/miniconda3/envs/MAT/lib/python3.7/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/lianyj/miniconda3/envs/MAT/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "train.py", line 641, in main
    subprocess_fn(rank=0, args=args, temp_dir=temp_dir)
  File "train.py", line 471, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "/home/lianyj/MAT/training/training_loop.py", line 175, in training_loop
    misc.print_module_summary(D, [img, mask_in, img_stg1, c])
  File "/home/lianyj/MAT/torch_utils/misc.py", line 218, in print_module_summary
    outputs = module(*inputs)
  File "/home/lianyj/miniconda3/envs/MAT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lianyj/MAT/networks/mat.py", line 963, in forward
    x_stg1 = self.Dis_stg1(torch.cat([masks_in - 0.5, images_stg1], dim=1))
  File "/home/lianyj/miniconda3/envs/MAT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lianyj/miniconda3/envs/MAT/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/lianyj/miniconda3/envs/MAT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lianyj/MAT/networks/basic_module.py", line 461, in forward
    return self.conv(x)
  File "/home/lianyj/miniconda3/envs/MAT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lianyj/MAT/networks/basic_module.py", line 97, in forward
    padding=self.padding)
  File "/home/lianyj/MAT/torch_utils/misc.py", line 101, in decorator
    return fn(*args, **kwargs)
  File "/home/lianyj/MAT/torch_utils/ops/conv2d_resample.py", line 147, in conv2d_resample
    return _conv2d_wrapper(x=x, w=w, padding=[py0,px0], groups=groups, flip_weight=flip_weight)
  File "/home/lianyj/MAT/torch_utils/ops/conv2d_resample.py", line 54, in _conv2d_wrapper
    return op(x, w, stride=stride, padding=padding, groups=groups)
  File "/home/lianyj/MAT/torch_utils/ops/conv2d_gradfix.py", line 37, in conv2d
    return _conv2d_gradfix(transpose=False, weight_shape=weight.shape, stride=stride, padding=padding, output_padding=0, dilation=dilation, groups=groups).apply(input, weight, bias)
  File "/home/lianyj/MAT/torch_utils/ops/conv2d_gradfix.py", line 112, in forward
    output = torch.nn.functional.conv2d(input=input, weight=weight, bias=bias, **common_kwargs)
RuntimeError: Given groups=1, weight of size [32, 5, 1, 1], expected input[8, 4, 512, 512] to have 5 channels, but got 4 channels instead

**Comment by 136LYJ** [comment]
# block_n   图像通道数: RGBA
# MAT_CelebA 图像通道数: RGB
通道数错误
