### ISSUE TITLE
pretrained/CelebA-HQ_512.pkl     _pickle.UnpicklingError: pickle data was truncated

### ISSUE THREAD

**Issue by 136LYJ** [fenglinglwb/MAT#120]
python generate_image.py --network pretrained/CelebA-HQ_512.pkl --dpath /home/data/PersonalData/lianyj/erase/cut/img4/img_expand-re512_rgb --mpath /home/data/PersonalData/lianyj/ENet-LGNet/mask/erase-rule-expand-re512-inv --outdir /home/data/PersonalData/lianyj/MAT/m-01
Loading data from: /home/data/PersonalData/lianyj/erase/cut/img4/img_expand-re512_rgb
Loading mask from: /home/data/PersonalData/lianyj/ENet-LGNet/mask/erase-rule-expand-re512-inv
Loading networks from: pretrained/CelebA-HQ_512.pkl
Traceback (most recent call last):
  File "generate_image.py", line 157, in <module>
    generate_images() # pylint: disable=no-value-for-parameter
  File "/home/lianyj/miniconda3/envs/MAT/lib/python3.7/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/lianyj/miniconda3/envs/MAT/lib/python3.7/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/lianyj/miniconda3/envs/MAT/lib/python3.7/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lianyj/miniconda3/envs/MAT/lib/python3.7/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/lianyj/miniconda3/envs/MAT/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "generate_image.py", line 100, in generate_images
    G_saved = legacy.load_network_pkl(f)['G_ema'].to(device).eval().requires_grad_(False) # type: ignore
  File "/home/lianyj/MAT/legacy.py", line 21, in load_network_pkl
    data = _LegacyUnpickler(f).load()
_pickle.UnpicklingError: pickle data was truncated

**Comment by wangyp33** [comment]
请问你解决了吗

**Comment by gqf123** [comment]
> 请问你解决了吗

请问你解决了吗
