### ISSUE TITLE
error: assert (name in src_tensors) or (not require_all)

### ISSUE THREAD

**Issue by yumengWang112** [fenglinglwb/MAT#16]
Traceback (most recent call last):
  File "generate_image.py", line 155, in <module>
    generate_images() # pylint: disable=no-value-for-parameter
  File "/root/anaconda3/envs/yyy/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/anaconda3/envs/yyy/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/anaconda3/envs/yyy/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/anaconda3/envs/yyy/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/anaconda3/envs/yyy/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "generate_image.py", line 102, in generate_images
    copy_params_and_buffers(G_saved, G, require_all=True)
  File "generate_image.py", line 46, in copy_params_and_buffers
    assert (name in src_tensors) or (not require_all)
AssertionError

i had fine-tuned the model in my own dataset and i want to test it, but it had the error ,Do you have any solutions?

**Comment by fenglinglwb** [comment]
If you adopt new parameters, just set 'require_all' to False.

**Comment by yumengWang112** [comment]
Thank you very much,I have solved this problem!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fenglinglwb/MAT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月26日(星期四) 晚上9:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fenglinglwb/MAT] error: assert (name in src_tensors) or (not require_all) (Issue #16)





 
If you adopt new parameters, just set 'require_all' to False.
