### ISSUE TITLE
Questions about error and mask path

### ISSUE THREAD

**Issue by naoki7090624** [fenglinglwb/MAT#2]
Thank you for sharing great works!!

I am interested in your works, and I have two questions.
1. I try to train the networks on custom dataset, but I got the following index error. Do you have the solutions?
```
Setting up augmentation...
Distributing across 1 GPUs...
Setting up training phases...
Downloading: "https://download.pytorch.org/models/vgg19-dcbb9e9d.pth" to /home/naoki/.cache/torch/hub/checkpoints/vgg19-dcbb9e9d.pth
100%|##########| 548M/548M [00:26<00:00, 22.0MB/s]
Exporting sample images...
Initializing logs...
Skipping tfevents export: No module named 'tensorboard'
Training for 50000 kimg...

tick 0     kimg 0.0      time 1m 47s       sec/tick 14.1    sec/kimg 1767.80 maintenance 92.5   cpumem 5.40   gpumem 37.61  augment 0.000
Evaluating metrics...
Traceback (most recent call last):
  File "train.py", line 648, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/home/naoki/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/naoki/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/naoki/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/naoki/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/naoki/.pyenv/versions/3.7.6/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "train.py", line 641, in main
    subprocess_fn(rank=0, args=args, temp_dir=temp_dir)
  File "train.py", line 471, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "/home/naoki/MAT/training/training_loop.py", line 418, in training_loop
    dataset_kwargs=val_set_kwargs, num_gpus=num_gpus, rank=rank, device=device)
  File "/home/naoki/MAT/metrics/metric_main.py", line 47, in calc_metric
    results = _metric_dict[metric](opts)
  File "/home/naoki/MAT/metrics/metric_main.py", line 93, in fid36k5_full
    fid = frechet_inception_distance.compute_fid(opts, max_real=36500, num_gen=36500)
  File "/home/naoki/MAT/metrics/frechet_inception_distance.py", line 31, in compute_fid
    rel_lo=0, rel_hi=1, capture_mean_cov=True, max_items=num_gen).get_mean_cov()
  File "/home/naoki/MAT/metrics/metric_utils.py", line 273, in compute_feature_stats_for_generator
    **data_loader_kwargs):
  File "/home/naoki/.pyenv/versions/3.7.6/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/naoki/.pyenv/versions/3.7.6/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/naoki/.pyenv/versions/3.7.6/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/naoki/.pyenv/versions/3.7.6/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/naoki/.pyenv/versions/3.7.6/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/naoki/.pyenv/versions/3.7.6/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/naoki/.pyenv/versions/3.7.6/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/naoki/MAT/datasets/dataset_512.py", line 265, in __getitem__
    image = self._load_raw_image(self._raw_idx[idx])
IndexError: index 2032 is out of bounds for axis 0 with size 2032
```

2. How can I specify the mask path for training?

**Comment by fenglinglwb** [comment]
1. The default evaluation metric is 'fid36k5_full', which requires the validation set to have 36k5 images. You can just define your own metric in the file 'metrics/metric_main.py' according to the number of images in the validation set.
2. The mask for training is randomly generated. If you want to specify the mask path, you need to adjust the logic in the 'datasets/dataset_xxx.py'.

**Comment by naoki7090624** [comment]
Thanks so much!! That is helpful!
