### ISSUE TITLE
Train on custom dataset

### ISSUE THREAD

**Issue by zhenzey** [fenglinglwb/MAT#22]
Thanks for the nice code! I was wondering whether I can train the model with my own dataset (It is a small one so I hope to train from the pretrained model on Places2).

**Comment by fenglinglwb** [comment]
Sure. You can initialize the model with the pre-trained weights by specifying 'resume' as the model path.

**Comment by Michaelwjh** [comment]
> Sure. You can initialize the model with the pre-trained weights by specifying 'resume' as the model path.
I followed your method, but it reported the following error. The pkl I used is CelebA-HQ_256.pkl, and the custom resolution is 256，could you tell me why? Thank you.

Constructing networks...
Resuming from "/root/MAT-Main/CelebA-HQ_256.pkl"
Traceback (most recent call last):
  File "train.py", line 651, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/root/miniconda3/envs/glcic/lib/python3.7/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/glcic/lib/python3.7/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/glcic/lib/python3.7/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/glcic/lib/python3.7/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/glcic/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "train.py", line 644, in main
    subprocess_fn(rank=0, args=args, temp_dir=temp_dir)
  File "train.py", line 474, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "/root/MAT-Main/training/training_loop.py", line 162, in training_loop
    misc.copy_params_and_buffers(resume_data[name], module, require_all=False)
  File "/root/MAT-Main/torch_utils/misc.py", line 160, in copy_params_and_buffers
    tensor.copy_(src_tensors[name].detach()).requires_grad_(tensor.requires_grad)
RuntimeError: The size of tensor a (256) must match the size of tensor b (512) at non-singleton dimension 1
