### ISSUE TITLE
An error occurred when train own data on pretrain model 

### ISSUE THREAD

**Issue by newprogrammer2022** [fenglinglwb/MAT#70]
Hi, thanks to your wonderful work.
I met a problem when training my  own data on pretrain model. I set the  resume= "pretrained/ffhq-res512-mirror-stylegan2-noaug.pkl" , but when the model was finally trained, the MappingNet only contained 2 layers, fc0 and fc1. So this model is not able to used in generat_image. 
Why did such situation happen, did I set wrong parameters or miss parts of some?
Thank you very much , looking forward to you reply!

**Comment by Fuze5k** [comment]
change this line in training/training_loop.py:
G = dnnlib.util.construct_class_by_name(**G_kwargs, **common_kwargs).train().requires_grad_(False).to(device) 

on this line, it fix problem for me:
G = Generator(z_dim=512, c_dim=0, w_dim=512, img_resolution=512, img_channels=3).train().requires_grad_(False).to(device) 

and add imports:
from networks.mat import Generator

**Comment by clcllllll** [comment]
> 

After making the modifications based on your suggestion, the training model encountered an error:

Traceback (most recent call last):
  File "train.py", line 652, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/data/conda_file/envs/MAT/lib/python3.7/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/data/conda_file/envs/MAT/lib/python3.7/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/data/conda_file/envs/MAT/lib/python3.7/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/conda_file/envs/MAT/lib/python3.7/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/data/conda_file/envs/MAT/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "train.py", line 645, in main
    subprocess_fn(rank=0, args=args, temp_dir=temp_dir)
  File "train.py", line 475, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "/data/zdz/MAT/training/training_loop.py", line 175, in training_loop
    img = misc.print_module_summary(G, [img_in, mask_in, z, c])
  File "/data/zdz/MAT/torch_utils/misc.py", line 218, in print_module_summary
    outputs = module(*inputs)
  File "/data/conda_file/envs/MAT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/zdz/MAT/networks/mat.py", line 895, in forward
    img = self.synthesis(images_in, masks_in, ws, noise_mode=noise_mode)
  File "/data/conda_file/envs/MAT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/zdz/MAT/networks/mat.py", line 831, in forward
    out_stg1 = self.first_stage(images_in, masks_in, ws, noise_mode=noise_mode)
  File "/data/conda_file/envs/MAT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/zdz/MAT/networks/mat.py", line 776, in forward
    x, x_size, mask = block(x, x_size, None)
  File "/data/conda_file/envs/MAT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/zdz/MAT/networks/mat.py", line 423, in forward
    x, mask = blk(x, x_size, mask)
  File "/data/conda_file/envs/MAT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/zdz/MAT/networks/mat.py", line 271, in forward
    x_windows = window_partition(shifted_x, self.window_size)  # nW*B, window_size, window_size, C
  File "/data/zdz/MAT/torch_utils/misc.py", line 101, in decorator
    return fn(*args, **kwargs)
  File "/data/zdz/MAT/networks/mat.py", line 48, in window_partition
    x = x.view(B, H // window_size, window_size, W // window_size, window_size, C)
RuntimeError: shape '[32, 0, 16, 0, 16, 180]' is invalid for input of size 368640
