### ISSUE TITLE
512x512 image training error

### ISSUE THREAD

**Issue by shyoon87** [fenglinglwb/MAT#78]
-- Error Message
Traceback (most recent call last):
  File "train.py", line 650, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "C:\Users\yoon\anaconda3\envs\mat\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\yoon\anaconda3\envs\mat\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\yoon\anaconda3\envs\mat\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\yoon\anaconda3\envs\mat\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\yoon\anaconda3\envs\mat\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "train.py", line 643, in main
    subprocess_fn(rank=0, args=args, temp_dir=temp_dir)
  File "train.py", line 473, in subprocess_fn
    training_loop.training_loop(rank=rank, **args)
  File "C:\Users\yoon\AI\MAT-main\training\training_loop.py", line 175, in training_loop
    misc.print_module_summary(D, [img, mask_in, img_stg1, c])
  File "C:\Users\yoon\AI\MAT-main\torch_utils\misc.py", line 218, in print_module_summary
    outputs = module(*inputs)
  File "C:\Users\yoon\anaconda3\envs\mat\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\yoon\AI\MAT-main\networks\mat.py", line 963, in forward
    x_stg1 = self.Dis_stg1(torch.cat([masks_in - 0.5, images_stg1], dim=1))
  File "C:\Users\yoon\anaconda3\envs\mat\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\yoon\anaconda3\envs\mat\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "C:\Users\yoon\anaconda3\envs\mat\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\yoon\AI\MAT-main\networks\basic_module.py", line 461, in forward
    return self.conv(x)
  File "C:\Users\yoon\anaconda3\envs\mat\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\yoon\AI\MAT-main\networks\basic_module.py", line 97, in forward
    padding=self.padding)
  File "C:\Users\yoon\AI\MAT-main\torch_utils\misc.py", line 101, in decorator
    return fn(*args, **kwargs)
  File "C:\Users\yoon\AI\MAT-main\torch_utils\ops\conv2d_resample.py", line 147, in conv2d_resample
    return _conv2d_wrapper(x=x, w=w, padding=[py0,px0], groups=groups, flip_weight=flip_weight)
  File "C:\Users\yoon\AI\MAT-main\torch_utils\ops\conv2d_resample.py", line 54, in _conv2d_wrapper
    return op(x, w, stride=stride, padding=padding, groups=groups)
  File "C:\Users\yoon\AI\MAT-main\torch_utils\ops\conv2d_gradfix.py", line 37, in conv2d
    return _conv2d_gradfix(transpose=False, weight_shape=weight.shape, stride=stride, padding=padding, output_padding=0, dilation=dilation, groups=groups).apply(input, weight, bias)
  File "C:\Users\yoon\AI\MAT-main\torch_utils\ops\conv2d_gradfix.py", line 116, in forward
    output = torch.nn.functional.conv2d(input=input, weight=weight, bias=bias, **common_kwargs)
RuntimeError: Given groups=1, weight of size [32, 5, 1, 1], expected input[1, 4, 512, 512] to have 5 channels, but got 4 channels instead

I made 20 images to practice 512x512 image training. The above error occurred. What could be the cause?

**Comment by 136LYJ** [comment]
我也是报错
