### ISSUE TITLE
Setting up PyTorch plugin "upfirdn2d_plugin"... Failed!

### ISSUE THREAD

**Issue by mingqizhang** [fenglinglwb/MAT#8]
I run the test code on linux and windows, there are the same problem?
Traceback (most recent call last):
  File "/data1/mingqi/MAT-main/torch_utils/ops/upfirdn2d.py", line 32, in _init
    _plugin = custom_ops.get_plugin('upfirdn2d_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])
  File "/data1/mingqi/MAT-main/torch_utils/custom_ops.py", line 110, in get_plugin
    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)
  File "/home/mingqi/.conda/envs/Mat/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 997, in load
    keep_intermediates=keep_intermediates)
  File "/home/mingqi/.conda/envs/Mat/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1213, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/mingqi/.conda/envs/Mat/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1560, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/home/mingqi/.conda/envs/Mat/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'upfirdn2d_plugin'

  warnings.warn('Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:\n\n' + traceback.format_exc())

**Comment by fenglinglwb** [comment]
Please see https://github.com/NVlabs/stylegan2-ada-pytorch/issues/35.

**Comment by klinic** [comment]
我按照做作者的设置，在TiTan上快速测试成功了

**Comment by yuanlinwang** [comment]
delete the files in "/home/username/.cache/torch_extensions/" it works finally!
