### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by clcllllll** [fenglinglwb/MAT#96]
Hello, I encountered this error when trying to load the trained model file for inference after training my own dataset：

Traceback (most recent call last):
  File "generate_image.py", line 160, in <module>
    generate_images() # pylint: disable=no-value-for-parameter
  File "/data/conda_file/envs/MAT/lib/python3.7/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/data/conda_file/envs/MAT/lib/python3.7/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/data/conda_file/envs/MAT/lib/python3.7/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/conda_file/envs/MAT/lib/python3.7/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/data/conda_file/envs/MAT/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "generate_image.py", line 106, in generate_images
    copy_params_and_buffers(G_saved, G, require_all=True)
  File "generate_image.py", line 49, in copy_params_and_buffers
    assert (name in src_tensors) or (not require_all)
AssertionError

**Comment by kzafeir** [comment]
I am facing the same problem have you found a solution?
